### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by sdinot** [Xat59/ansible-role-vsftpd#9]
Dear Xat59,

I would love to use your role in my project, but the license of your role is not very explicit. There is only a vague mention of BSD license (is it [BSD 2-Clause](https://opensource.org/licenses/BSD-2-Clause) or [BSD 3-Clause](https://opensource.org/licenses/BSD-3-Clause)?) in the meta/main.yml file.

Could you announce more clearly the license of your project in your README file and in the project medadata on Github?

Here is an example: <https://github.com/PyratLabs/ansible-role-helm>
* The license (BSD 3-clause) [is announced](https://github.com/PyratLabs/ansible-role-helm#license) in the README.md file
* A copy of the license is provided in the [LICENSE.txt](https://github.com/PyratLabs/ansible-role-helm/blob/master/LICENSE.txt) file
* The license is declared in the metadata of the project on Github and it appears in the vertical menu on the right.

**Comment by sdinot** [comment]
I thank you for taking my issue into account and, beyond that, for your work which will greatly simplify mine.

However, I notice that you have abandoned the BSD license in favor of the GNU LGPL v3. This is not a problem for me, but it proves that I was right to ask for clarification on this subject ;)

Thanks, and all the best to you!

**Comment by Xat59** [comment]
Thanks for the feedback.

Enjoy it and don't hesitate to give us more feedback on this role.
All the best !
